Added "underscore" and "undescore.string" to dependecies
Loader requiring "undescore" and "undescore.string" which are not included in package.json
https://github.com/chrisenytc/generator-demi/blob/master/app/templates/lib/loader.js#L19-20

So after fresh install "npm start" will cause errors:
Error: Cannot find module 'underscore'
Error: Cannot find module 'underscore.string'